# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'google_signin_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for google_signin_demo
  pod 'Google/SignIn'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
end
